<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>IndQuestResults.Extensions.Collections.Tests.Unit</RootNamespace>
    <AssemblyName>IndQuestResults.Extensions.Collections.Tests.Unit</AssemblyName>
  </PropertyGroup>


  <ItemGroup>


  <PackageReference Include="IndQuestResults" />
  </ItemGroup>
</Project>


