<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>IndQuestResults.Tests.Performance</RootNamespace>
    <AssemblyName>IndQuestResults.Tests.Performance</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <UseLocalRefs Condition="'$(UseLocalRefs)' == ''">false</UseLocalRefs>
  </PropertyGroup>
  <ItemGroup Condition="'$(UseLocalRefs)' == 'true'">
    <ProjectReference Include="..\..\src\IndQuestResults\IndQuestResults.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalRefs)' != 'true'">
    <PackageReference Include="IndQuestResults" />
  </ItemGroup>


</Project>
